version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: loomsql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: loombase
      MYSQL_USER: loomuser
      MYSQL_PASSWORD: loompass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql 

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loombackend
    restart: always
    expose:
      - 8000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: loombase
      DATABASE_USER: loomuser
      DATABASE_PASSWORD: loompass
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loomfrontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: loom-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data: {}
  redis_data: {}
